<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EntityFramework\Micropack.EF\Micropack.EF.csproj" />
    <ProjectReference Include="..\Micropack.Localization\Micropack.Localization.csproj" />
  </ItemGroup>

</Project>
